### PR TITLE
Add null check to getSearchResults & getPageResults

### PR DESCRIPTION
**Pull request by caranad**
Hey, so I revised your getSearchResults and getPageResults function: rather than throwing an error each time the parseResultsHTML returns null (which can be annoying), I made it return an empty page results array.

Let me know if you are ok with this change!

### CODE REVIEW

**Comment by mwpenny** [comment]
Hi, thanks for your interest! Under which conditions are you running into this error? It should only occur if the HTML couldn't be parsed (I.e., not a valid Kijiji results page, or Kijiji changed their markup and the scraper needs to be updated). You shouldn't be getting this error under normal circumstances.

**Comment by caranad** [comment]
No worries! I was looking through the code after playing around with it and getting an error when using the search function, with the following parameters:

locationId: 1700273
categoryId: 0
keywords: "Islanders jersey"
minPrice: 0
maxPrice: 100

I found that results were returned when kijiji.search() was passed with these parameters for page 1, but when it reaches page 2, an exception is hit and thus I am unable to retrieve the results. Let me know if you are getting the same results with those parameters in place

**Comment by caranad** [comment]
Otherwise, it might be confusing if the exception is returned BUT when I try the same search on Kijiji, I get results.

**Comment by mwpenny** [comment]
I think I know what this is. I recently changed some of the criteria for when to stop advancing pages. It doesn't look like `getSearchResults()` is properly detecting when to stop.

When you run this on Kijiji does their results page have 2 pages, or only 1?

**Comment by caranad** [comment]
Only 1, if I'm not mistaken.

**Comment by caranad** [comment]
Hey Matt, any updates on this pull request?

**Comment by caranad** [comment]
Hey any updates on what should be done about this pull request? Should I close it or something if no further action is to be taken?

**Comment by mwpenny** [comment]
Hi, sorry I've been pretty busy lately. The fact that there was only 1 page confirms what I thought. I'd like to rework the pagination logic next time I get some free time but this logic works. Thanks for the PR! Just a few minor tweaks and it's good to go

**Comment by mwpenny** [comment]
I'm on mobile and can't add in-line comments for some reason. Here's my feedback:

Lines 123-124: you removed a comment. Please add it back

Line 128: No need for a comment about lack of exception

Line 129: you can remove this entire if and just add `|| []` to `pageResults` in the final return

Line 157: Please remove this added newline

**Comment by caranad** [comment]
Oh my bad - I wasn't aware you were busy... apologies if I may have disturbed you unnecessarily. 

No worries - I'm glad I could help out with this library a bit! As requested I've updated search.js to meet the above recommendation. If there's anything else that's still missing please let me know :)

**Comment by mwpenny** [comment]
No worries! I just meant it's been why it's taken me a while to respond sometimes. Sorry about that.

I missed something earlier. Your changes to `getSearchResults()` only add the page results to the overall results after the check for the "end search" condition. This could result in making an extra request than necessary. Can you undo the changes in this function? In the event of no results, nothing will be added to the final results, as expected. But if there *are* results, we will bail out as early as possible if we've retrieved enough.

One final thing, can you increment the patch version number in `package.json` please (c in a.b.c; see https://semver.org/)

**Comment by caranad** [comment]
Hi Matt, I think I have an idea of what you need me to do, and I've applied the changes in my latest commit (f2f6f6a). Please review them and let me know if there is anything else that needs to be done.

Thanks!

**Comment by caranad** [comment]
Hey Matt just wondering if you've seen my latest commit yet? Let me know when you can. Thanks!

**Comment by mwpenny** [comment]
@caranad So sorry for the long delays. A lot of unexpected things have been going on. I should have more time for this project in a few months when things settle down. I appreciate your contribution and will resolve the small merge conflicts I just introduced by fixing the scraper to work with Kijiij's new markup (#22), then merge to master.

I actually found a better way to solve this - Kijiji stores a flag in a JavaScript object in the returned page that indicates whether or not it is the last page (search for `isLastPage` in the HTML if you are interested). For now, this fix works perfectly fine. Thanks again and sincere apologies for the back and forth!

**Pull request merged**
