### PR TITLE
my changes. tests dont pass with the latest node

### PR DESCRIPTION
**Pull request by jsproull**

### CODE REVIEW

**Comment by jsproull** [comment]
nice

**Comment by mwpenny** [comment]
Thanks for heads up. I have made some changes to get builds + tests running on newer Node.js versions (I found some other problems in addition to the ones you fixed here). I also dropped Node 10 from the CI workflow and added Node 16 (the current LTS). See #64.

I noticed that you updated the ad ID regex in `api-scraper`. Did you find a new type of ad with a different ID format? If yes, could you link to an example?

**Comment by jsproull** [comment]
Hi Matt,

 Sorry, I removed my PR because I meant to just merge it into my fork for
now as there was still a build error.. Didn't have time to track it down
yet.

Here's an example of why I changed the regex:

https://www.kijiji.ca/v-other-business-industrial/canada/seagate-dual2lp-1-06gb-5400rpm-fast-scsi-50-pin-512kb-cache-3-5-inch-internal-hard-drive/cas_19010495

 On further searches, I've found other ones like:


https://www.kijiji.ca/v-cars-trucks/ottawa/2019-kia-forte-ex-ivt-apple-carplay-heated-steering/m3218327

 and also a couple that start with 'cXXXXX'

**Comment by mwpenny** [comment]
No problem. I just fixed some other build errors. Try pulling the latest and let me know if it resolves your issues.

As for the IDs with letter prefixes, these are commercial/partner listings, which are not currently supported due to the fact that their format can vary from standard Kijiji ads and they are usually spammy. Are these types of ads relevant to what you are trying to do?

**Comment by jsproull** [comment]
Ah, interesting about the commercial ads. I never noticed that, but now
that you mention it, those are not relevant. I guess I should just filter
them from my search results. Is there an attribute on the ad listings that
indicate they are promoted ads?

Just built the main branch and ran the tests and everything is looking good
in node 16 👍🏼

**Pull request closed without merging**
